<?php

namespace Tests;

use App\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Notification;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
    use DatabaseMigrations;
    use WithFaker;

    /**
     * @param User|null $user
     * @return TestCase
     */
    public function login(User $user = null): self
    {
        if (!$user) {
            $user = create(User::class);
        }

        $this->actingAs($user);

        return $this;
    }

    protected function setUp():void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Event::fake();
        Mail::fake();
        Notification::fake();
    }}
